# Generated by Django 4.2 on 2023-04-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0008_student_no_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterDates',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('currentSemester', models.BooleanField(default=False)),
            ],
        ),
    ]
