# Generated by Django 4.1.7 on 2023-04-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0009_semesterdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='semester',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
