# Generated by Django 4.1.7 on 2023-04-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0010_alter_availability_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.URLField(default='static/images/favicons/Blue_logo.png'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='profile_picture',
            field=models.URLField(default='static/images/favicons/Blue_logo.png'),
        ),
    ]
