# Generated by Django 4.1.7 on 2023-05-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0011_student_profile_picture_tutor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
