# Generated by Django 4.1.7 on 2023-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0013_alter_availability_timeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='timeblock',
            field=models.CharField(choices=[('A', '8:00 AM - 9:00 AM'), ('B', '9:00 AM - 10:00 AM'), ('C', '10:00 AM - 11:00 AM'), ('D', '11:00 AM - 12:00 PM'), ('E', '12:00 PM - 1:00 PM'), ('F', '1:00 PM - 2:00 PM'), ('G', '2:00 PM - 3:00 PM'), ('H', '3:00 PM - 4:00 PM'), ('I', '4:00 PM - 5:00 PM')], max_length=1),
        ),
    ]
