# Generated by Django 4.2 on 2023-05-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0015_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.URLField(blank=True, default='static/images/favicons/Blue_logo.png', null=True),
        ),
    ]
