# Generated by Django 4.1.7 on 2023-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0016_alter_tutor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ums_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
